### ISSUE TITLE
Domänenmodell

### ISSUE THREAD

**Issue by gksu123** [Kplacken/EPWS2020SerttasPlackenhohn#1]
Hallo Uwe, wir haben schonmal einen Domänenmodell entworfen und würden uns über einen Feedback freuen. 

![Domänenmodell](https://user-images.githubusercontent.com/56268580/99157929-a6970b80-26cd-11eb-8732-a361529a0bbc.jpg)

ps: Life's Good ist der Name unserer App ;)

LG Eda

**Comment by umuesse** [comment]
Ich denke, dass einige eurer entdeckten Probleme auch stark in Kombination auftreten können. 
Aus der Sicht von Entwurfsmustern könntet ihr das evtl. noch ein wenig deutlicher machen. 

Symptome und Ursachen sowie erste Maßnahmen verschwimmen hier aus meiner Sicht ein wenig.
