### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by Kplacken** [Kplacken/EPWS2020SerttasPlackenhohn#2]
Hallo Uwe,

wir haben gerade das Problem, dass wir unser Repo nicht auf privat stellen können, da wir dann unser Wiki nicht mehr sehen können. Ist das okay, wenn unser Repo öffentlich ist oder sollen wir mal ein neues Repo erstellen?
![Screenshot (59)](https://user-images.githubusercontent.com/56312783/99267346-20d9a400-2824-11eb-9726-5435e6e8d116.png)

Liebe Grüße
Kimberly

**Comment by umuesse** [comment]
Aus meiner Sicht spricht nichts gegen ein öffentliches Repo, solange ihr alle Rechte an euren Dokumenten und deren Inhalten besitzt. 
Habt ihr für euren Account zu einem Education-Account gemacht? Dann sollte das eigentlich auch mit dem Wiki im privaten Mode klappen.

**Comment by Kplacken** [comment]
Hab meinen Account jetzt zu einem Education-Account gemacht und jetzt funktioniert es. 
Vielen Dank. :-)
