### ISSUE TITLE
Audit 1

### ISSUE THREAD

**Issue by Kplacken** [Kplacken/EPWS2020SerttasPlackenhohn#4]
Hallo Uwe,
wir haben noch eine Frage zur PowerPoint.
Ist es in Ordnung, wenn wir das Exposé und das Problem Szenario als Bild hinzufügen?
Die Texte sind leider etwas länger und auch nicht kurz zu fassen.
Wir haben schon die Wörter gezählt und haben mit den Texten, den anderen Folien und den Notizen etwas unter 3000 Worten.

**Comment by umuesse** [comment]
Das ist vollkommen in Ordnung
