### ISSUE TITLE
Abgabe Audit 4 und Use-Case

### ISSUE THREAD

**Issue by gksu123** [Kplacken/EPWS2020SerttasPlackenhohn#6]
Hallo Uwe,
die Abgabe für EP ist bis Samstag den 20.02. vorgesehen, jedoch wissen wir nicht, bis wie viel Uhr wir das abgeben müssen. 
Ist die Abgabe wieder regulär bis 23:59 Uhr gedacht?

Außerdem haben wir noch eine Frage zu unserem Use-Case. Wir wollten einmal ein allgemeines Use-Case mit in die Präsentation reinnehmen, (siehe Screenshot)
![Use-Case LG (2)](https://user-images.githubusercontent.com/56268580/108514922-c4739e00-72c4-11eb-9d47-cdee47173b27.png)
(Vermerk: Grün kam neu dazu und Blau wurde nicht umgesetzt)

und dann noch mal ein Use-Case, wo wir nur die Funktionen mit Trinken, Umfrage/Befragung und Auswertung, also kurz alles was wir beim Audit 4 präsentieren wollen als Use-Case "Beschreibung des Prototypen" mit auf die Folien nehmen. (siehe Screenshot)
![Use-Case Audit4](https://user-images.githubusercontent.com/56268580/108515310-364be780-72c5-11eb-913b-460985458c6a.jpeg)

Also wir haben bis auf die Favoriten und dem Mondkalender alle Funktionen implementiert, daher sind die 2 Funktionen in dem allgemeinen Use-Case "blau" markiert und stehen für "nicht Umgesetzt". Auswertung und Datenbank hatten wir bei dem vorherigen Use-Case nicht drin, deswegen haben wir die "grün" markiert. 

Da wir alle Funktionen bis auf die Auswertung schon in Audit 3 Präsentiert hatten, würden wir uns bei Audit 4 gerne nur auf die Auswertung konzentrieren, deswegen haben wir nochmal ein Use-Case mit nur diesen Funktionen gemacht, die wir auch am Montag präsentieren werden.

Würden gerne vor dem 4. Audit, das letzte mal ein Feedback von dir nehmen.

Schonmal danke im voraus.

Liebe Grüße
Eda

**Comment by umuesse** [comment]
Als Uhrzeit ist 23:59Uhr angesetzt, das ist richtig. 
Wann hättet ihr denn heute noch Zeit?

**Comment by gksu123** [comment]
Also ich hätte jetzt Zeit.

**Comment by umuesse** [comment]
https://th-koeln.zoom.us/j/89044342884?pwd=eVFUbDhubzc5QXU3MGpaZjhwTU5qZz09

**Comment by umuesse** [comment]
Könntet ihr die Issues eures Projektes bitte schließen, sodass sie bei mir nicht mehr im Issue-Tracking autauchen? 
Das wäre sehr nett von euch ;-)
